# Generated by Django 2.1.4 on 2018-12-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('patch_level', models.CharField(max_length=50)),
            ],
        ),
    ]
