# Generated by Django 2.1.4 on 2018-12-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webserver',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
