# Generated by Django 2.1.4 on 2018-12-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=100)),
                ('os_type', models.CharField(max_length=50)),
                ('os_patch_level', models.CharField(max_length=50)),
                ('environment', models.CharField(max_length=50)),
            ],
        ),
    ]
