# Generated by Django 2.1.4 on 2018-12-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_hostapplications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostapplications',
            name='database_ids',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='hostapplications',
            name='webserver_ids',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
