# Generated by Django 2.1.4 on 2018-12-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20181208_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostapplications',
            name='database_ids',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hostapplications',
            name='webserver_ids',
            field=models.CharField(max_length=50),
        ),
    ]
